version: '2.2'
services:

  nginx-web:
    image: nginx
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: ${NGINX_WEB:-nginx-web}
    restart: always
    ports:
      - "${HTTP_BIND:-0.0.0.0}:${HTTP_PORT:-80}:${HTTP_PORT:-80}"
      - "${HTTPS_BIND:-0.0.0.0}:${HTTPS_PORT:-443}:${HTTPS_PORT:-443}"
    volumes:
      - ${NGINX_FILES_PATH:-./data/proxy}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./data/proxy}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./data/proxy}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./data/proxy}/certs:/etc/nginx/certs:ro
      - ${NGINX_FILES_PATH:-./data/proxy}/htpasswd:/etc/nginx/htpasswd:ro
      - ${NGINX_FILES_PATH:-./data/proxy}/certs/dhparam.pem:/etc/nginx/dhparam/dhparam.pem
    logging:
      options:
        max-size: ${NGINX_WEB_LOG_MAX_SIZE:-4m}
        max-file: ${NGINX_WEB_LOG_MAX_FILE:-10}

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup ${NGINX_WEB:-nginx-web} -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: ${DOCKER_GEN:-nginx-gen}
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${NGINX_FILES_PATH:-./data/proxy}/templates/:/etc/docker-gen/templates/:ro
    volumes_from:
      - nginx-web
    logging:
      options:
        max-size: ${NGINX_GEN_LOG_MAX_SIZE:-2m}
        max-file: ${NGINX_GEN_LOG_MAX_FILE:-10}
#    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: ${LETS_ENCRYPT:-nginx-letsencrypt}
    restart: always
    volumes:
      - ${NGINX_FILES_PATH:-./data/proxy}/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-web
    environment:
      NGINX_DOCKER_GEN_CONTAINER: ${DOCKER_GEN:-nginx-gen}
      NGINX_PROXY_CONTAINER: ${NGINX_WEB:-nginx-web}
    logging:
      options:
        max-size: ${NGINX_LETSENCRYPT_LOG_MAX_SIZE:-2m}
        max-file: ${NGINX_LETSENCRYPT_LOG_MAX_FILE:-10}

#networks:
#  default:
#    external:
#      name: ${NETWORK:-webproxy}

